apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: digital-twin-frontend
  labels:
    app: digital-twin-frontend
    part-of: digital-twin
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
    
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: digital-twin-frontend:latest
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 2Gi
