apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-twin-frontend
  labels:
    app: digital-twin-frontend
    part-of: digital-twin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digital-twin-frontend
  template:
    metadata:
      labels:
        app: digital-twin-frontend
    spec:
      containers:
        - name: frontend
          image: image-registry.openshift-image-registry.svc:5000/ishaduttamaharana-dev/digital-twin-frontend:latest
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
