apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digital-twin-db-pvc
  namespace: digital-twin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi # or standard OpenShift storage class
