apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digital-twin-db-data
  labels:
    app: digital-twin-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
