apiVersion: v1
kind: Secret
metadata:
  name: digital-twin-backend-secret
  labels:
    app: digital-twin-backend
    part-of: digital-twin
type: Opaque
stringData:
  DB_USERNAME: "digital_twin"
  DB_PASSWORD: "digital_twin"
  DB_KIND: "postgresql"
